services:
  app:
    build:
      context: .
    image: base64-to-image-app
    ports:
      - '3000'
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - base64-to-image-network
    deploy:
      replicas: 5

  nginx:
    image: nginx:latest
    ports:
      - '13301:80'
    volumes:
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-global.conf:/etc/nginx/modules-enabled/global.conf
    networks:
      - base64-to-image-network
networks:
  base64-to-image-network:
    driver: bridge
